name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  myci:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache RubyGems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Install dependencies
        run: sh ./bootstrap.sh

      - name: Run Tests
        run: fastlane tests_github_actions
